[package]
name = "rust-ml"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rust-mnist = "0.1.4"
tokio = { version = "1.12", features = ["rt", "macros"] }